### ISSUE TITLE
Uncaught URI Error: URI Malformed for Trello Cards When clicking "Show Dependencies"

### ISSUE THREAD

**Issue by ThomThio** [DanielPopOut/graph-dependencies#3]
![image](https://user-images.githubusercontent.com/9068521/97655922-2358a180-1aa1-11eb-9ad1-ee9d870afcb3.png)

**Comment by ThomThio** [comment]
1. Clicked on Button "Show Dependencies"
2. In console, shows URI malformed from dependencyManager.tsx line 98.

**Comment by DanielPopOut** [comment]
Hello @ThomThio,

I investigated this morning and found out cards name with a percent "%" in their name are not correctly decoded.
Could you confirm you have cards with a % in their name ? Or make a debug to find out the cardName that caused this error ? 

I'll fix it today

**Comment by ThomThio** [comment]
Hi @DanielPopOut , not using any percentages.

The title is a relatively simple one:
![image](https://user-images.githubusercontent.com/9068521/97679118-cde7b900-1acf-11eb-9407-dd17f0f67bed.png)

714 is the parent. The only other special character could be the "#".

**Comment by DanielPopOut** [comment]
I published the extension on the Chrome Web store as v2.8
Should be available in a few hours 👍

**Comment by DanielPopOut** [comment]
@ThomThio Was your problem fixed ? 
I added a console.error to print the string causing the error in the console.
**It would be useful if you could confirm it was the sentence printed up there that created the error ?**

Lastly if you can [add a review on the chrome store (what you like, waht you'd like as updates) it would be amazing 👍 ](https://chrome.google.com/webstore/detail/graph-dependency-for-trel/ppbndnpfbahiilhalfmbkfnhkaohjbdo)

**Comment by ThomThio** [comment]
Hi Daniel thanks for pushing this code.

I see that indeed there are some cards with % in them

The try-catch makes the dependencies appear on the left, but doesn't seem to 'save', perhaps because of the error?

![image](https://user-images.githubusercontent.com/9068521/97998123-afadf000-1e24-11eb-837a-8276f16d4c22.png)

**Comment by DanielPopOut** [comment]
I think I got what you mean. 
It looks like dependencies updates on the graph (with cmd + click) is not saved
But if you add a dependency clicking on button it is saved.
Is it that ? 

I'll update it so every change on the graph or with button be saved

**Comment by DanielPopOut** [comment]
Oh boy... I also tested with several urls --> 
dependencies are saved not by board id but by url you use... 
Exemple : 
Let's take a project with a trello id "vkctuxI"
If I go on : 
>  trello.com/b/vkctuxI
>  trello.com/b/vkctuxI/
>  trello.com/b/vkctuxI/nom-du-projet

I'll get 3 differents project dependencies saved in the local storage 😢

I create a new issue for that

**Comment by ThomThio** [comment]
Ah, that explains it... actually if you need to have uniqueness and map each one back to its parent, how about hashing the URL so you won't get decoding errors? And reversing the hash to obtain the original of course.
